### ISSUE TITLE
Feature Request: Get All Commits

### ISSUE THREAD

**Issue by RavenLLevitt** [AZ0228/Commit-Getter#8]
I recommend adding a feature that allows you to get all requests instead of just commits from a specific branch. Alternatively, allow the selecting of multiple branches, currently if you need commits from 2 different branches you must run the program twice since you cannot added the same repo multiple times.

<img width="967" alt="image" src="https://github.com/AZ0228/Commit-Getter/assets/103865865/f70b02ef-16df-4fad-b4eb-b75e72814c0a">

**Comment by AZ0228** [comment]
added a feature where you can choose up to 3 branches
